# Variables
NAME = libft.a
CC = cc
FLAGS = -Wall -Werror -Wextra

# GNL: get next line
GNL_FOLDER = get_next_line/
GNL_SRCS = \
			get_next_line.c \
			get_next_line_utils.c
GNL_OBJS = $(GNL_SRCS:.c=.o)

# Math
MATH_FOLDER = math/
MATH_SRCS = \
			ft_abs.c \
			ft_max.c

MATH_OBJS = $(MATH_SRCS:.c=.o)

# Char
CHAR_FOLDER = char/
CHAR_SRCS = \
			ft_isalnum.c \
			ft_isalpha.c \
			ft_isascii.c \
			ft_isdigit.c \
			ft_isprint.c \
			ft_isspace.c \
			ft_tolower.c \
			ft_toupper.c
CHAR_OBJS = $(CHAR_SRCS:.c=.o)

# String
STRING_FOLDER = string/
STRING_SRCS = \
			ft_equals.c \
			ft_is_empty.c \
			ft_joinstrs.c \
			ft_split.c \
			ft_str_array_len.c \
			ft_strchr.c \
			ft_strcmp.c \
			ft_strdup.c \
			ft_striteri.c \
			ft_strjoin.c \
			ft_strlcat.c \
			ft_strcpy.c \
			ft_strlcpy.c \
			ft_strlen.c \
			ft_strmapi.c \
			ft_strncmp.c \
			ft_strnstr.c \
			ft_strrchr.c \
			ft_strtrim.c \
			ft_substr.c
STRING_OBJS = $(STRING_SRCS:.c=.o)

# Memory
MEMORY_FOLDER = memory/
MEMORY_SRCS = \
			ft_bzero.c \
			ft_calloc.c \
			ft_free_str_array.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_memcpy.c \
			ft_memmove.c \
			ft_memset.c
MEMORY_OBJS = $(MEMORY_SRCS:.c=.o)

# Parse
PARSE_FOLDER = parse/
PARSE_SRCS = \
			ft_atoi.c \
			ft_itoa.c \
			ft_number_len.c
PARSE_OBJS = $(PARSE_SRCS:.c=.o)

# Write
WRITE_FOLDER = write/
WRITE_SRCS = \
			ft_putchar_fd.c \
			ft_putendl_fd.c \
			ft_putendl.c \
			ft_putnbr_fd.c \
			ft_putstr_fd.c \
			ft_putstr.c
WRITE_OBJS = $(WRITE_SRCS:.c=.o)

OBJ = $(GNL_OBJS) $(MATH_OBJS) $(CHAR_OBJS) $(STRING_OBJS) $(MEMORY_OBJS) $(PARSE_OBJS) $(WRITE_OBJS)

# Rules
.PHONY: all clean fclean re bonus

# Compiles libft
all: $(NAME)

# Creates libft.a from .o files
$(NAME): libft.h $(OBJ)
	ar -r $(NAME) $(OBJ)

# Compiles .c files into .o files
$(GNL_OBJS): $(addprefix $(GNL_FOLDER), $(GNL_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(GNL_FOLDER), $(GNL_SRCS))

$(MATH_OBJS): $(addprefix $(MATH_FOLDER), $(MATH_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(MATH_FOLDER), $(MATH_SRCS))

$(CHAR_OBJS): $(addprefix $(CHAR_FOLDER), $(CHAR_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(CHAR_FOLDER), $(CHAR_SRCS))

$(STRING_OBJS): $(addprefix $(STRING_FOLDER), $(STRING_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(STRING_FOLDER), $(STRING_SRCS))

$(MEMORY_OBJS): $(addprefix $(MEMORY_FOLDER), $(MEMORY_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(MEMORY_FOLDER), $(MEMORY_SRCS))

$(PARSE_OBJS): $(addprefix $(PARSE_FOLDER), $(PARSE_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(PARSE_FOLDER), $(PARSE_SRCS))

$(WRITE_OBJS): $(addprefix $(WRITE_FOLDER), $(WRITE_SRCS))
	$(CC) $(FLAGS) -c $(addprefix $(WRITE_FOLDER), $(WRITE_SRCS))

# Cleans temporary files but not the executable
clean:
	rm -f $(OBJ)

# Cleans the same as clean + the executable (full clean)
fclean: clean
	rm -f $(NAME)

# Cleans and recompiles the libft
re: fclean all
